<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();
$layout->setLayout('1-column-blue-grey');

$layout->subheader = 'Welcome to OpenConext Collaboration Infrastructure EngineBlock - Internal endpoint';
?>
        <p>
            Welcome to the OpenConext COIN Internal endpoint, this endpoint is for OpenConext administrators and services only!<br />
            If you believe you are seeing this in error, please contact <a href="help@demo.openconext.org">help@demo.openconext.org</a>.<br />
            <br />
            See also: <a href="/service">/service</a>.<br />
            See also: <a href="/social">/social</a>.<br />
            See also: <a href="/cron">/cron</a>.
        </p>
    </body>
</html>
