<?php
/** @var Zend_Layout $layout */
$layout = $this->layout();
$layout->setLayout('default');

// Set Layout properties
$layout->wide       = true;
$layout->title = $layout->title. ' - Metadata & Certificates';
$layout->header = $layout->title;
$layout->subheader = 'IdP Certificate and Metadata';
$layout->displayLanguageSwitcher = false;

/** @var Zend_Config $keyPairs */
$keyPairs = EngineBlock_ApplicationSingleton::getInstance()->getConfiguration()->encryption->keys;
$keyPairIds = array();
if ($keyPairs) {
    $keyPairIds = array_keys($keyPairs->toArray());
}
?>
<div id="engine-main-page" class="box">
  <div class="mod-content">

    <div class="main">
      <h1><?php echo $this->layout()->subheader; ?></h1>
        <dl class="metadata-certificates-list">
            <dt>
                The Public SAML Signing certificate of the OpenConext IdP
            </dt>
            <dd>
                <ul>
                    <li><a href="/authentication/idp/certificate">Open link</a></li>
                    <?php foreach ($keyPairIds as $keyId): ?>
                    <li><a href="/authentication/idp/certificate/key:<?=$keyId?>">Open link</a></li>
                    <?php endforeach; ?>
                </ul>
            </dd>
            <dt>
                The Public SAML metadata (the entity descriptor) of the OpenConext IdP Proxy
            </dt>
            <dd>
                <ul>
                    <li><a href="/authentication/idp/metadata">Open link</a></li>
                    <?php foreach ($keyPairIds as $keyId): ?>
                        <li><a href="/authentication/idp/metadata/key:<?=$keyId?>">Open link</a></li>
                    <?php endforeach; ?>
                </ul>
            </dd>
            <dt>
                The Public SAML metadata (the entities descriptor) for all the OpenConext IdPs
            </dt>
            <dd>
                <ul>
                    <li><a href="/authentication/proxy/idps-metadata">Open link</a></li>
                    <?php foreach ($keyPairIds as $keyId): ?>
                        <li><a href="/authentication/proxy/idps-metadata/key:<?=$keyId?>">Open link</a></li>
                    <?php endforeach; ?>
                </ul>
            </dd>
            <dt>
                <p class="strong">Metadata below is only relevant for key rollover or in
                case you want a custom WAYF for your SP</p>
            </dt>
            <dt>
                The Public SAML metadata (the entity descriptor) of the OpenConext IdP Proxy for SP
                with entityID "urn:example.org". Please replace "urn:example.org" with the entityID
                of your own SP before testing this metadata request. The resulting metadata will include
                the public key specific to your Service Provider, which, in the case of key rollover,
                MAY be different from the regular public key.
            </dt>
            <dd>
                <ul>
                    <li><a href="/authentication/idp/metadata?sp-entity-id=urn:example.org">Open link</a></li>
                    <?php foreach ($keyPairIds as $keyId): ?>
                        <li><a href="/authentication/idp/metadata/key:<?=$keyId?>?sp-entity-id=urn:example.org">Open link</a></li>
                    <?php endforeach; ?>
                </ul>
            </dd>
            <dt>
                The Public SAML metadata (the entities descriptor) of the OpenConext IdPs which allow
                access to SP with entityID "urn:example.org". Please replace "urn:example.org" with
                the entityID of your own SP before testing. The resulting metadata will include all
                OpenConext IdPs that allow access to the service, as well as the SP metadata, if
                configured for OpenConext. Please note this information is generated dynamically, so
                the number of available IdPs may change over time.
            </dt>
            <dd>
                <ul>
                    <li><a href="/authentication/proxy/idps-metadata?sp-entity-id=urn:example.org">Open link</a></li>
                    <?php foreach ($keyPairIds as $keyId): ?>
                        <li><a href="/authentication/proxy/idps-metadata/key:<?=$keyId?>?sp-entity-id=urn:example.org">Open link</a></li>
                    <?php endforeach; ?>
                </ul>

            </dd>
        </dl>
    </div>

    <div class="main">
      <h1>SP Certificate and Metadata</h1>
      <dl class="metadata-certificates-list">
          <dt>
              Test authentication with an identity provider.
          </dt>
          <dd>
            <ul>
              <li><a href="/authentication/sp/debug">Open link</a></li>
            </ul>
          </dd>
          <dt>
              The Public SAML Signing certificate of the OpenConext SP
          </dt>
          <dd>
              <ul>
                  <li><a href="/authentication/sp/certificate">Open link</a></li>
                  <?php foreach ($keyPairIds as $keyId): ?>
                      <li><a href="/authentication/sp/certificate/key:<?=$keyId?>">Open link</a></li>
                  <?php endforeach; ?>
              </ul>
          </dd>
          <dt>
              The Public SAML metadata (the entity descriptor) of the OpenConext SP Proxy
          </dt>
          <dd>
              <ul>
                  <li><a href="/authentication/sp/metadata">Open link</a></li>
                  <?php foreach ($keyPairIds as $keyId): ?>
                      <li><a href="/authentication/sp/metadata/key:<?=$keyId?>">Open link</a></li>
                  <?php endforeach; ?>
              </ul>
          </dd>
        </dl>
      </div>

      <div class="main">
        <h1>eduGAIN Metadata</h1>
        <dl class="metadata-certificates-list">
          <dt>
              The OpenConext eduGain SAML metadata consists out of all IdPs and SPs that are included of
              the <a href="http://mds.edugain.org/" data-external-link="true" target="_blank">eduGain metadata</a>.
          </dt>
          <dd>
              <ul>
                  <li><a href="/authentication/proxy/edugain-metadata">Open link</a></li>
                  <?php foreach ($keyPairIds as $keyId): ?>
                      <li><a href="/authentication/proxy/edugain-metadata/key:<?=$keyId?>">Open link</a></li>
                  <?php endforeach; ?>
              </ul>
          </dd>
        </dl>
      </div>

    </div>
  </div>
